Web/BookReadingEvent.Web/Models/SignUp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookReadingEvent.Web.Models
{
    public class SignUp
    {
        public int UserID { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "This Field is required")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "This Field is required")]
        public string LastName { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This Field is required")]
        public string EmailID { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Field is required")]
        [StringLength(20,MinimumLength =5,ErrorMessage ="Password lenght atleast 5 character")]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#&])[A-Za-z\d@$!%*#?&]{5,}$", ErrorMessage = "Please enter strong password")]
        public string Password { get; set; }
        public string InvitedEvent { get; set; }

    }
}

Web/BookReadingEvent.Web/Controllers/SignupController.cs
using BookReadingEvent.Core.ValueObjects;
using BookReadingEvent.ProductDomain.AppServices;
using BookReadingEvent.ProductDomain.AppServices.DTOs;
using BookReadingEvent.ProductDomain.AppServices.Facade;
using BookReadingEvent.ProductDomain.AppServices.Factory;
using BookReadingEvent.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace BookReadingEvent.Web.Controllers
{
    public class SignupController : Controller
    {

        /* private readonly IUserService _userService;
         // userservice is called dependency and get  injected 
         public SignupController(IUserService userService)
         {
             _userService = userService;
         }
         */
        //        private readonly IEventFacade _eventFacade; 
        private readonly FacadeFactory _facadeFactory;
        /*public SignupController(IEventFacade eventFacade)
        {
            _eventFacade = eventFacade;
        }*/
        public SignupController(FacadeFactory facadeFactory)
        {
            _facadeFactory = facadeFactory;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]  
        public IActionResult Index(SignUp userDetails)  
        {
            if (ModelState.IsValid)
            {
                SignUpDTO obj = new SignUpDTO
                {
                    EmailID = userDetails.EmailID,
                    FirstName = userDetails.FirstName,
                    LastName = userDetails.LastName,
                    Password = userDetails.Password
                };
                EventFacade _eventFacade = (EventFacade)_facadeFactory.GetFacade("IEventFacade");
                bool user = _eventFacade.AddUser(obj);
                if (user == true)
                {
                    return RedirectToAction("Index", "Login");
                }
            }
            return View();

        }
    }
}

Web/BookReadingEvent.Web/Views/Signup/Index.cshtml
@model SignUp;
@section Styles {

    <link href="~/css/SignUp.css" rel="stylesheet" />
}
<div class="outerdiv">
    <div class="insidediv" style="background-color:ghostwhite;">
        <div>
            <h3>SignUp Page </h3>
            <hr />
        </div>
        <form method="post" asp-action="Index" asp-controller="Signup">
            <div class="mb-3">
                <label asp-for="FirstName" class="form-label validate">First Name</label>
                <input asp-for="FirstName" class="form-control">
                <span asp-validation-for="FirstName" style="color:red;"></span>
            </div>
            <div class="mb-3">
                <label asp-for="LastName" class="form-label validate">Last Name</label>
                <input asp-for="LastName" class="form-control">
                <span asp-validation-for="LastName" style="color:red;"></span>
            </div>
            <div class="mb-3">
                <label asp-for="EmailID" class="form-label validate">Email address</label>
                <input asp-for="EmailID" class="form-control">
                <span asp-validation-for="EmailID" style="color:red"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label validate">Password</label>
                <input asp-for="Password" class="form-control">
                <span asp-validation-for="Password" style="color:red;"></span>
            </div>
            <input type="submit" value="SignUp" class="btn btn-primary" />
        </form>
    </div>
</div>