Web/BookReadingEvent.Web/Controllers/CreateEventController.cs
using BookReadingEvent.ProductDomain.AppServices;
using BookReadingEvent.ProductDomain.AppServices.DTOs;
using BookReadingEvent.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using BookReadingEvent.Web.Infrastructure;
using BookReadingEvent.ProductDomain.AppServices.Facade;
using BookReadingEvent.ProductDomain.AppServices.Factory;

namespace BookReadingEvent.Web.Controllers
{
    [CustomAuthFilter(Roles ="admin,user")]
    public class CreateEventController : Controller
    {
        private readonly FacadeFactory _facadeFactory;
        //private readonly IEventFacade _eventFacade;
       /* public CreateEventController(IEventFacade eventfacade)
        {
            _eventFacade = eventfacade;
        }*/
        public CreateEventController(FacadeFactory facadeFactory)
        {
            _facadeFactory = facadeFactory;
        }
        public IActionResult Index()
        {
            ViewBag.emailId = HttpContext.Session.GetString("EmailId");
            return View();
        }
        [HttpPost]
        public IActionResult Index(Event EventDetails)
        { 
            CreateEventDTO newEvent = new CreateEventDTO();
            newEvent.Date = EventDetails.Date;
            newEvent.Description = EventDetails.Description;
            newEvent.Duration = EventDetails.Duration;
            newEvent.InviteByEmail = EventDetails.InviteByEmail;
            newEvent.Location = EventDetails.Location;
            newEvent.OtherDetails = EventDetails.OtherDetails;
            newEvent.StartTime = EventDetails.StartTime;
            newEvent.Title = EventDetails.Title;
            newEvent.Type = EventDetails.Type;
            newEvent.Creator = HttpContext.Session.GetString("EmailId");
            EventFacade _eventFacade = (EventFacade)_facadeFactory.GetFacade("IEventFacade");
            _eventFacade.AddEvent(newEvent);
           // _userService.AddEvent(newEvent);
            if (EventDetails.InviteByEmail != null)
            {
                string EmailID = HttpContext.Session.GetString("EmailId");
                //  _userService.TagInvitedEventToUser(EventDetails.InviteByEmail, EmailID);
                _eventFacade.TagInvitedEventToUser(EventDetails.InviteByEmail, EmailID);
            }
            
            return RedirectToAction("Index","MyEvent");
        }
    }
}

Web/BookReadingEvent.Web/Views/CreateEvent/Index.cshtml
@model Event;
@{

    Layout = "_LayoutEvent";
}
@section Styles {
    <link href="~/css/CreateEvent.css" rel="stylesheet" />

}

<div class="outerdiv">
    <div class="insidediv">
        <div style="width:80%;margin-left:5%;">
            <div>
                <h3>Create Event </h3>
                <hr />
            </div>
            @using (Html.BeginForm("", "CreateEvent", FormMethod.Post))
            {
                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "fs-5 validate" })


                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

                </div>

                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "fs-5 validate" })

                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker " } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>


                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "fs-5 validate" })

                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>

                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "fs-5 validate" })

                    @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control timepicker " } })
                </div>


                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "fs-5 validate" })


                    <div>@Html.RadioButtonFor(model => model.Type, "public", new { htmlAttributes = new { @class = "form-control " } }) Public</div>
                    <div>@Html.RadioButtonFor(model => model.Type, "private", new { htmlAttributes = new { @class = "form-control " } }) Private</div>

                </div>


                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "fs-5 validate" })
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @max = 4, @min = 0 } })
                </div>

                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "fs-5 validate" })

                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="form-group mb-3">

                    @Html.LabelFor(model => model.OtherDetails, htmlAttributes: new { @class = "fs-5 validate" })

                    @Html.EditorFor(model => model.OtherDetails, new { htmlAttributes = new { @class = "form-control" } })
                </div>


                <div class="form-group mb-4">

                    @Html.LabelFor(model => model.InviteByEmail, htmlAttributes: new { @class = "fs-5" })

                    @Html.EditorFor(model => model.InviteByEmail, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="row mb-5" style="margin-left:5px;">
                    <button type="submit" class="btn btn-success fs-5 ps-5 pe-5 ">Create</button>
                    <input type="reset" value="Clear" style="margin-left:10px;" class="btn btn-primary " />
                    <!-- <button type="submit" class="btn btn-primary fs-5 ps-5 pe-5 " style="margin-left:10px;">Clear</button> -->
                </div>

            }
        </div>
    </div>
</div>