Web/BookReadingEvent.Web/Controllers/GetEventController.cs
using BookReadingEvent.ProductDomain.AppServices;
using BookReadingEvent.ProductDomain.AppServices.DTOs;
using BookReadingEvent.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using AutoMapper;
using BookReadingEvent.Web.Infrastructure;
using BookReadingEvent.ProductDomain.AppServices.Facade;
using BookReadingEvent.ProductDomain.AppServices.Factory;

namespace BookReadingEvent.Web.Controllers
{
   
    public class GetEventController : Controller
    {
        private readonly FacadeFactory _facadeFactory;
       // private readonly IEventFacade _eventFacade;
        private readonly IMapper _mapper;  
       /* public GetEventController(IEventFacade eventFacade ,IMapper mapper)
        {
            _mapper = mapper;
            _eventFacade = eventFacade;
        }*/
        public GetEventController(FacadeFactory facadeFactory,IMapper mapper)
        {
            _facadeFactory = facadeFactory;
            _mapper = mapper;
        }
        public IActionResult Index(int id , string name,string layout)
        {
            ViewBag.checkLayout = layout;
            ViewBag.emailId = HttpContext.Session.GetString("EmailId");
            ViewBag.check = name;
            EventFacade _eventFacade = (EventFacade)_facadeFactory.GetFacade("IEventFacade");
            if (_mapper.Map<List<CommentDTO>, List<Comment>>(_eventFacade.GetAllComments(id)).Count > 0)
            {
                ViewBag.count = 1;
            }
            ViewBag.Comments = _mapper.Map<List<CommentDTO>, List<Comment>>(_eventFacade.GetAllComments(id));
            CreateEventDTO newEvent = GetEventById(id);
            Event storeEvent = new Event();
            storeEvent.Date = newEvent.Date;
            storeEvent.Description = newEvent.Description;
            storeEvent.Title = newEvent.Title;
            storeEvent.StartTime = newEvent.StartTime;
            storeEvent.Location = newEvent.Location;
            storeEvent.Duration = newEvent.Duration;
            storeEvent.EventId = newEvent.EventId;
            storeEvent.OtherDetails = newEvent.OtherDetails;
            storeEvent.Creator = newEvent.Creator;
            return View(storeEvent);
        }
        public CreateEventDTO GetEventById(int id)
        {
            EventFacade _eventFacade = (EventFacade)_facadeFactory.GetFacade("IEventFacade");
            return  _eventFacade.GetEventById(id);
        }
        public IActionResult DeleteByEventId(int id)
        {
            EventFacade _eventFacade = (EventFacade)_facadeFactory.GetFacade("IEventFacade");
            _eventFacade.DeleteByEventId(id);
            return RedirectToAction("Index","MyEvent");
        }
        
    } 
}

Web/BookReadingEvent.Web/Controllers/MyEventController.cs
using BookReadingEvent.ProductDomain.AppServices.DTOs;
using BookReadingEvent.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using BookReadingEvent.ProductDomain.AppServices;
using BookReadingEvent.Web.Infrastructure;
using BookReadingEvent.ProductDomain.AppServices.Facade;
using BookReadingEvent.ProductDomain.AppServices.Factory;

namespace BookReadingEvent.Web.Controllers
{
    [CustomAuthFilter(Roles ="admin,user")]
    public class MyEventController : Controller
    {
        /* private readonly ICreateEventService _eventServices;
         public MyEventController(ICreateEventService eventser)
         {
             _eventServices = eventser;
         }*/
        //  private readonly IEventFacade _eventFacade;
        private readonly FacadeFactory _facadeFactory;
       /* public MyEventController(IEventFacade eventFacade)
        {
            _eventFacade = eventFacade;
        }*/
        public MyEventController(FacadeFactory facadeFactory)
        {
            _facadeFactory = facadeFactory;
        }
        public IActionResult Index()
        {
            ViewBag.emailId = HttpContext.Session.GetString("EmailId");
            ViewBag.MyEvents = MyEvents();
            return View();
        }
        public List<Event> MyEvents()
        {
            List<Event> result = new List<Event>();
            var email = HttpContext.Session.GetString("EmailId");
            EventFacade _eventFacade = (EventFacade)_facadeFactory.GetFacade("IEventFacade");
            List<CreateEventDTO> store = _eventFacade.MyEvents(email);
            foreach (var x in store)
            {
                Event showEvent = new Event();
                showEvent.Date = x.Date;
                showEvent.Description = x.Description;
                showEvent.Duration = x.Duration;
                showEvent.InviteByEmail = x.InviteByEmail;
                showEvent.Location = x.Location;
                showEvent.OtherDetails = x.OtherDetails;
                showEvent.StartTime = x.StartTime;
                showEvent.Title = x.Title;
                showEvent.Type = x.Type;
                showEvent.EventId = x.EventId;
                result.Add(showEvent);
            }
            return result;
        }
    }
}

Web/BookReadingEvent.Web/Views/MyEvent/Index.cshtml
@{
    Layout = "_LayoutEvent";
}
@section Styles {
    <link href="~/css/HomeView.css" rel="stylesheet" />
}
<div style="display: flex; flex-direction: column; align-items: center;">
    <div style="width: 1240px;">
        <h3 class="display-4" style="text-align:center;">My Events</h3>
        <div style="display:flex; gap:20px; flex-wrap: wrap;">
            @if (ViewBag.MyEvents.Count != 0)
            {


                @foreach (var e in ViewBag.MyEvents)
                {
                    <a asp-action="Index" asp-controller="GetEvent" asp-route-id="@e.EventId" asp-route-name="MyEvent">
                        <div class="card shadow es234CardWrapper" style="min-width: 200px; margin-bottom: 3px; float: left; margin-right: 3px; padding:12px;">

                            <h5 class="card-title primaryClr">@e.Title</h5>
                            <h6 class="card-subtitle mb-2 "><b>Description:-&nbsp;</b> @e.Description</h6>
                            <h6 class="card-subtitle mb-2"><b>Date:-&nbsp;</b> @e.Date.ToShortDateString()</h6>
                            <h6 class="card-subtitle mb-2 "><b>Duration:-&nbsp;</b> @e.Duration hrs</h6>
                            <h6 class="card-subtitle mb-2"><b>Location:-&nbsp;</b> @e.Location</h6>
                            <h6 class="card-subtitle mb-2"><b>Start Time:-&nbsp;</b> @e.StartTime</h6>
                        </div>
                    </a>
                }
            }
            else
            {
                <h3 style="color: lightgray; text-align:center;">You have not created any event till now</h3>
            }
        </div>
    </div>
</div>